inherit_gem:
  rubocop-govuk:
    - "config/default.yml"
    - "config/rails.yml"

inherit_mode:
  merge:
    - Exclude

Metrics/BlockLength:
  Exclude:
    - "Rakefile"
    - "**/*.rake"
    - "spec/**/*.rb"
    - "config/routes.rb"
    - "config/initializers/*.rb"
    - "config/environments/*.rb"

Rails/OutputSafety:
  Enabled: false
