development:
  encoding: utf8
  adapter: mysql2
  database: contacts_development
  username: contacts
  password: contacts
test:
  encoding: utf8
  adapter: mysql2
  database: contacts_test
  username: contacts
  password: contacts
production:
  encoding: utf8
  adapter: mysql2
  database: contacts_development
  username: contacts
  password: contacts
