development:
  encoding: utf8
  adapter: mysql2
  database: hmrc_contacts_development
  username: hmrc_contacts
  password: hmrc_contacts
test:
  encoding: utf8
  adapter: mysql2
  database: hmrc_contacts_test
  username: hmrc_contacts
  password: hmrc_contacts
